language: node_js
node_js:
  - 'node'
script: yarn build
after_success: yarn coveralls
before_deploy: yarn doc
deploy:
  provider: surge
  project: ./docs/
  domain: fenugreek-collections.surge.sh
  skip_cleanup: true
